# fly.toml app configuration file generated for squakr on 2025-02-21T11:39:51+00:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "squakr"
kill_signal = "SIGINT"
kill_timeout = "5s"
primary_region = "cdg"

[experimental]
  auto_rollback = true

[processes]
  app = "npm start"

[[services]]
  internal_port = 8_080
  processes = [ "app" ]
  protocol = "tcp"

[services.concurrency]
  hard_limit = 25
  soft_limit = 20
  type = "connections"

[[services.ports]]
  force_https = true
  handlers = [ "http" ]
  port = 80

[[services.ports]]
  handlers = [ "tls", "http" ]
  port = 443

[[services.tcp_checks]]
  grace_period = "1s"
  interval = "15s"
  timeout = "2s"
